### ISSUE TITLE
Module not found: Can't resolve 'classnames'

### ISSUE THREAD

**Issue by heyaware** [coded-bear/react-otpinput#10]
Getting this error when integrating into a NextJS app. Adding the `classnames` to my package.json solves it, but you may want to move `classnames` to the this modules `dependencies` instead of `devDependencies`?

<img width="718" alt="" src="https://user-images.githubusercontent.com/103811786/202600170-5104efd8-b8a9-4c02-ab54-c600aedbf1c0.png">

**Comment by coded-bear** [comment]
Thanks for your interest in my project.

The new version of the package already has a fix.

https://github.com/coded-bear/react-otp-field/pull/11/files

**Comment by heyaware** [comment]
That fixed it. Thanks @coded-bear
