### ISSUE TITLE
I want to prevent user to type hyphen and dot but after implementing it with onKeyDown event, I am not able to focus back to previous input box

### ISSUE THREAD

**Issue by abhayjeetg** [coded-bear/react-otpinput#12]
__
![image](https://user-images.githubusercontent.com/119564069/221101089-62eb0209-a0bb-4728-9360-a1f379eb062e.png)
### ### ****

**Comment by coded-bear** [comment]
Thank you for your interest in my package.
If you want to prevent the user from typing in specific characters, you can use the onChangeRegex props.
Example: https://coded-bear.github.io/react-otp-field/

**Comment by abhayjeetg** [comment]
OKay I got it! Issue was with **isTypeNumber** prop, I have removed it and its working fine, thank you.
